### ISSUE TITLE
Upgrade openocd to 0.10.0

### ISSUE THREAD

**Issue by erwango** [zephyrproject-rtos/meta-zephyr-sdk#85]
Some SoCs require openocd 0.10.0 for flash.
Update zephyr SDK to openocd 0.10.0

**Comment by tracernz** [comment]
e.g. SAM E70 (missing targets/atsamv.cfg, and if I copy that from my system openocd, missing flash driver atsamv). Need to see if I can easily convince zephyr env to use my system openocd...

**Comment by tracernz** [comment]
For the record, `export OPENOCD=openocd` will use openocd on your PATH (i.e. `which openocd`).

**Comment by nashif** [comment]
try 0.9.2

**Comment by tracernz** [comment]
Works fine now, thanks. :+1:
