### ISSUE TITLE
Build break on OSX 10.13.1

### ISSUE THREAD

**Issue by VinceGa** [zephyrproject-rtos/meta-zephyr-sdk#89]
OSX 10.13.1 
Docker verison: 17.11.0-ce
I did : pokyuser@8c5dd3d6d40e:/workdir$ ./meta-zephyr-sdk/scripts/meta-zephyr-sdk-build.sh
I got ERROR:

Call stack:
 ERROR: quilt-native-0.64-r0 do_populate_sysroot: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:sstate_task_postfunc(d)
     0003:
File: '/workdir/poky/meta/classes/sstate.bbclass', lineno: 672, function: sstate_task_postfunc
     0668:
     0669:python sstate_task_postfunc () {
     0670:    shared_state = sstate_state_fromvars(d)
     0671:
 *** 0672:    sstate_install(shared_state, d)
     0673:    for intercept in shared_state['interceptfuncs']:
     0674:        bb.build.exec_func(intercept, d, (d.getVar("WORKDIR", True),))
     0675:    omask = os.umask(0o002)
     0676:    if omask != 0o002:
File: '/workdir/poky/meta/classes/sstate.bbclass', lineno: 276, function: sstate_install
     0272:
     0273:    # Run the actual file install
     0274:    for state in ss['dirs']:
     0275:        if os.path.exists(state[1]):
 *** 0276:            oe.path.copyhardlinktree(state[1], state[2])
     0277:
     0278:    for postinst in (d.getVar('SSTATEPOSTINSTFUNCS', True) or '').split():
     0279:        # All hooks should run in the SSTATE_INSTDIR
     0280:        bb.build.exec_func(postinst, d, (sstateinst,))
File: '/workdir/poky/meta/lib/oe/path.py', lineno: 91, function: copyhardlinktree
     0087:            source = source + '%s/*' % src
     0088:        else:
     0089:            source = src
     0090:        cmd = 'cp -afl --preserve=xattr %s %s' % (source, dst)
 *** 0091:        subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT)
     0092:    else:
     0093:        copytree(src, dst)
     0094:
     0095:def remove(path, recurse=True):
File: '/usr/lib/python3.4/subprocess.py', lineno: 620, function: check_output
     0616:            process.wait()
     0617:            raise
     0618:        retcode = process.poll()
     0619:        if retcode:
 *** 0620:            raise CalledProcessError(retcode, process.args, output=output)
     0621:    return output
     0622:
     0623:
     0624:def list2cmdline(seq):
Exception: subprocess.CalledProcessError: Command 'cp -afl --preserve=xattr /workdir/poky/build-zephyr-tools/tmp/work/x86_64-linux/quilt-native/0.64-r0/sysroot-destdir/workdir/poky/build-zephyr-tools/tmp/sysroots/x86_64-linux/* /workdir/poky/build-zephyr-tools/tmp/sysroots/x86_64-linux' returned non-zero exit status 1

Subprocess output:
cp: cannot create hard link ‘/workdir/poky/build-zephyr-tools/tmp/sysroots/x86_64-linux/usr/share/quilt/compat/awk’ to ‘/workdir/poky/build-zephyr-tools/tmp/work/x86_64-linux/quilt-native/0.64-r0/sysroot-destdir/workdir/poky/build-zephyr-tools/tmp/sysroots/x86_64-linux/usr/share/quilt/compat/awk’: No such file or directory

ERROR: quilt-native-0.64-r0 do_populate_sysroot: Function failed: sstate_task_postfunc
ERROR: Logfile of failure stored in: /workdir/poky/build-zephyr-tools/tmp/work/x86_64-linux/quilt-native/0.64-r0/temp/log.do_populate_sysroot.1505
ERROR: Task (/workdir/poky/meta/recipes-devtools/quilt/quilt-native_0.64.bb:do_populate_sysroot) failed with exit code '1'

It seems odd: can't create a hard link in poky? Or something related to OSX cp -l?

**Comment by nashif** [comment]
this sdk is not supported on macOS
